num1=int(input("enter value for num1"))
num2=int(input("enter value for num2"))
print(num1<num2)
num1=int(input("enter value for num1"))
num2=int(input("enter value for num2"))
print(num1>num2)
num1=int(input("enter value for num1"))
num2=int(input("enter value for num2"))
print(num1<=num2)
num1=int(input("enter value for num1"))
num2=int(input("enter value for num2"))
print(num1==num2)